export const JobTypes = {
  GET_JOBS: "GET_JOBS",
  GET_JOBS_BY_JOBTYPE: "GET_JOBS_BY_JOBTYPE",
  GET_JOBS_BY_DEPT: "GET_JOBS_BY_DEPT",
  GET_JOBS_BY_SCHEDULE: "GET_JOBS_BY_SCHEDULE",
  GET_JOBS_BY_EXPERIENCE: "GET_JOBS_BY_EXPERIENCE",
  GET_JOBS_BY_SEARCH: "GET_JOBS_BY_SEARCH",
  GET_SORTED_ARRAY_BY_LOCATION: "GET_SORTED_ARRAY_BY_LOCATION",
  GET_SORTED_ARRAY_BY_ROLE: "GET_SORTED_ARRAY_BY_ROLE",
  GET_SORTED_ARRAY_BY_DEPT: "GET_SORTED_ARRAY_BY_DEPT",
  GET_SORTED_ARRAY_BY_EDUCATION: "GET_SORTED_ARRAY_BY_EDUCATION",
  GET_SORTED_ARRAY_BY_EXPERIENCE: "GET_SORTED_ARRAY_BY_EXPERIENCE",
};
